name: Debug
on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        ARGOCD_REPO_SSH: ${{ secrets.ARGOCD_REPO_SSH }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        DEV_MAILCHIMP_ID: ${{ secrets.DEV_MAILCHIMP_ID }}
        DEV_NODE_PROVIDER: ${{ secrets.DEV_NODE_PROVIDER }}
        DEV_SECRET_COOKIE_PASSWORD: ${{ secrets.DEV_SECRET_COOKIE_PASSWORD }}
        FACEBOOK_PIXEL: ${{ secrets.FACEBOOK_PIXEL }}
        FACEBOOK_VERIFY_ID: ${{ secrets.FACEBOOK_VERIFY_ID }}
        GLEAM_REWARD_URL: ${{ secrets.GLEAM_REWARD_URL }}
        GOOGLE_ANALYTICS_ID_DEV: ${{ secrets.GOOGLE_ANALYTICS_ID_DEV }}
        GOOGLE_ANALYTICS_ID_PROD: ${{ secrets.GOOGLE_ANALYTICS_ID_PROD }}
        PROD_MAILCHIMP_ID: ${{ secrets.PROD_MAILCHIMP_ID }}
        PROD_NODE_PROVIDER: ${{ secrets.PROD_NODE_PROVIDER }}
        PROD_SECRET_COOKIE_PASSWORD: ${{ secrets.PROD_SECRET_COOKIE_PASSWORD }}
        ROOT_SEED: ${{ secrets.ROOT_SEED }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        SERVICE_URL_DEV: ${{ secrets.SERVICE_URL_DEV }}
        SERVICE_URL_PROD: ${{ secrets.SERVICE_URL_PROD }}
      run: |
        echo "ARGOCD_REPO_SSH ${ARGOCD_REPO_SSH}" >> secrets.txt
        echo "AWS_REGION ${AWS_REGION}" >> secrets.txt
        echo "DEV_MAILCHIMP_ID ${DEV_MAILCHIMP_ID}" >> secrets.txt
        echo "DEV_NODE_PROVIDER ${DEV_NODE_PROVIDER}" >> secrets.txt
        echo "DEV_SECRET_COOKIE_PASSWORD ${DEV_SECRET_COOKIE_PASSWORD}" >> secrets.txt
        echo "FACEBOOK_VERIFY_ID ${FACEBOOK_VERIFY_ID}" >> secrets.txt
        echo "GLEAM_REWARD_URL ${GLEAM_REWARD_URL}" >> secrets.txt
        echo "GOOGLE_ANALYTICS_ID_DEV ${GOOGLE_ANALYTICS_ID_DEV}" >> secrets.txt
        echo "GOOGLE_ANALYTICS_ID_PROD ${GOOGLE_ANALYTICS_ID_PROD}" >> secrets.txt
        echo "PROD_MAILCHIMP_ID ${PROD_MAILCHIMP_ID}" >> secrets.txt
        echo "PROD_NODE_PROVIDER ${PROD_NODE_PROVIDER}" >> secrets.txt
        echo "PROD_SECRET_COOKIE_PASSWORD ${PROD_SECRET_COOKIE_PASSWORD} >> secrets.txt
        echo "ROOT_SEED ${ROOT_SEED}" >> secrets.txt
        echo "SENTRY_AUTH_TOKEN ${SENTRY_AUTH_TOKEN}" >> secrets.txt
        echo "SENTRY_DSN ${SENTRY_DSN}" >> secrets.txt
        echo "SERVICE_URL_DEV ${SERVICE_URL_DEV}" >> secrets.txt
        echo "SERVICE_URL_PROD ${SERVICE_URL_PROD}" >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
